### ISSUE TITLE
Bug: Hide and Seek

### ISSUE THREAD

**Issue by ichsansandy** [arnoldnekemiah/portfolio-new#15]
# Bug

Hi @arnoldnekemiah 

I found that your mobile menu not functioning as it should be
in line 8 main.js you forget to put method ```.add()``` to adding class to the element

In your main.js
```
  function openMenu() {
    mobileMenu.style.display = 'flex';
    body.classList('menu-open');
  }
```

Suggestion for fixing the bug
```
  function openMenu() {
    mobileMenu.style.display = 'flex';
    body.classList.open('menu-open');
  }
```

Hopefully, it solves your problem
Cheers

Ichsan

**Comment by arnoldnekemiah** [comment]
Correct! Your on point
